version: '3'
services:
  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672

  minio:
    image: girder/minio-nonroot:latest
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
    volumes:
      - fsdata:/var/lib/minio

volumes:
  dbdata:
  fsdata:
