version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/resonantgeodata
    ports:
      - 8000:8000
    depends_on:
      # TODO: https://docs.docker.com/compose/startup-order/
      - db
      - rabbitmq
      - minio

  worker:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: ["celery", "worker", "--app", "rgd.celery", "--loglevel", "info", "--without-heartbeat"]
    env_file: ./dev/.env.docker-compose
    environment:
      - TMPDIR=/tmp/rgd_worker
    volumes:
      - .:/opt/resonantgeodata
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp/rgd_worker:/tmp/rgd_worker
    depends_on:
      - db
      - rabbitmq
      - minio

  flower:
    image: mher/flower
    command: ["--broker=amqp://rabbitmq:5672/", "--url_prefix=flower"]
