version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/django
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - minio

  celery:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: [
      "celery", "worker",
      "--app", "rgd.celery",
      "--loglevel", "info",
      "--without-heartbeat"
    ]
    env_file: ./dev/.env.docker-compose
    environment:
      - TMPDIR=/tmp/rgd_worker
    volumes:
      - .:/opt/django
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${DOCKER_CMD:-/usr/bin/docker}:/usr/bin/docker
      - /tmp/rgd_worker:/tmp/rgd_worker
    depends_on:
      - postgres
      - rabbitmq
      - minio

  flower:
    image: mher/flower
    command: ["--broker=amqp://rabbitmq:5672/", "--url_prefix=flower"]
