version: '3'
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: rgd
      POSTGRES_PASSWORD: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:management
    volumes:
      - mqdata:/var/lib/rabbitmq

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioAdminAccessKey
      MINIO_SECRET_KEY: minioAdminSecretKey
    volumes:
      - fsdata:/data

volumes:
  dbdata:
  fsdata:
  mqdata:
