# Generated by Django 3.1.5 on 2021-01-09 11:45

from django.db import migrations, models
import django.db.models.deletion
import rgd.geodata.models.geometry.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20210107_1807'),
        ('geodata', '0002_auto_20210111_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmvfile',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AlterField(
            model_name='geometryarchive',
            name='file',
            field=models.OneToOneField(help_text='This must be an archive (`.zip` or `.tar`) of a single shape (`.shp`, `.dbf`, `.shx`, etc.).', on_delete=django.db.models.deletion.CASCADE, to='core.file', validators=[rgd.geodata.models.geometry.base.validate_archive]),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AlterField(
            model_name='kwcocoarchive',
            name='image_archive',
            field=models.OneToOneField(help_text='An archive (.tar or .zip) of the images referenced by the spec file (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kwcoco_image_archive', to='core.file'),
        ),
        migrations.AlterField(
            model_name='kwcocoarchive',
            name='spec_file',
            field=models.OneToOneField(help_text='The JSON spec file.', on_delete=django.db.models.deletion.CASCADE, related_name='kwcoco_spec_file', to='core.file'),
        ),
    ]
